# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nfs/home/camsi6/Documents/Projet_CVA6/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.srcs/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xci
# IP: The module: 'xlnx_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/home/camsi6/Documents/Projet_CVA6/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_clk_gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /nfs/home/camsi6/Documents/Projet_CVA6/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /nfs/home/camsi6/Documents/Projet_CVA6/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /nfs/home/camsi6/Documents/Projet_CVA6/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.srcs/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xci
# IP: The module: 'xlnx_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/home/camsi6/Documents/Projet_CVA6/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /nfs/home/camsi6/Documents/Projet_CVA6/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /nfs/home/camsi6/Documents/Projet_CVA6/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
