set_property SRC_FILE_INFO {cfile:/home/utilisateur/Bureau/projet_M2/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master_in_context.xdc rfile:../../../../../xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master_in_context.xdc id:1 order:EARLY scoped_inst:i_axi_dwidth_converter_dm_master} [current_design]
set_property SRC_FILE_INFO {cfile:/home/utilisateur/Bureau/projet_M2/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave_in_context.xdc rfile:../../../../../xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave_in_context.xdc id:2 order:EARLY scoped_inst:i_axi_dwidth_converter_dm_slave} [current_design]
set_property SRC_FILE_INFO {cfile:/home/utilisateur/Bureau/projet_M2/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_blk_mem_gen/xlnx_blk_mem_gen.gen/sources_1/ip/xlnx_blk_mem_gen/xlnx_blk_mem_gen/xlnx_blk_mem_gen_in_context.xdc rfile:../../../../../xilinx/xlnx_blk_mem_gen/xlnx_blk_mem_gen.gen/sources_1/ip/xlnx_blk_mem_gen/xlnx_blk_mem_gen/xlnx_blk_mem_gen_in_context.xdc id:3 order:EARLY scoped_inst:i_xlnx_blk_mem_gen} [current_design]
set_property SRC_FILE_INFO {cfile:/home/utilisateur/Bureau/projet_M2/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen/xlnx_clk_gen_in_context.xdc rfile:../../../../../xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen/xlnx_clk_gen_in_context.xdc id:4 order:EARLY scoped_inst:i_xlnx_clk_gen} [current_design]
set_property SRC_FILE_INFO {cfile:/home/utilisateur/Bureau/projet_M2/cva6-softcore-contest/corev_apu/fpga/constraints/zybo_z7_20.xdc rfile:../../../../../constraints/zybo_z7_20.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/utilisateur/Bureau/projet_M2/cva6-softcore-contest/corev_apu/fpga/constraints/cva6_fpga.xdc rfile:../../../../../constraints/cva6_fpga.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:/home/utilisateur/Bureau/projet_M2/cva6-softcore-contest/corev_apu/fpga/cva6_fpga.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:7} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins i_axi_dwidth_converter_dm_master/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_axi_dwidth_converter_dm_master]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins i_axi_dwidth_converter_dm_slave/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_axi_dwidth_converter_dm_slave]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins i_xlnx_blk_mem_gen/s_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_xlnx_blk_mem_gen]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name clk_sys [get_ports clk_sys]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name i_xlnx_clk_gen/clk_out1 -source [get_pins i_xlnx_clk_gen/clk_in1] -edges {1 2 3} -edge_shift {0.000 4.333 8.667} [get_pins i_xlnx_clk_gen/clk_out1]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name i_xlnx_clk_gen/clk_out2 -source [get_pins i_xlnx_clk_gen/clk_in1] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins i_xlnx_clk_gen/clk_out2]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name i_xlnx_clk_gen/clk_out3 -source [get_pins i_xlnx_clk_gen/clk_in1] -edges {1 2 3} -edge_shift {2.000 2.000 2.000} [get_pins i_xlnx_clk_gen/clk_out3]
set_property src_info {type:SCOPED_XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name i_xlnx_clk_gen/clk_out4 -source [get_pins i_xlnx_clk_gen/clk_in1] -edges {1 2 3} -edge_shift {0.000 6.000 12.000} [get_pins i_xlnx_clk_gen/clk_out4]
set_property src_info {type:SCOPED_XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk_sys]
set_property src_info {type:SCOPED_XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk_sys]
set_property src_info {type:SCOPED_XDC file:4 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_xlnx_clk_gen]
set_property src_info {type:XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk_sys]
set_property src_info {type:XDC file:5 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -to [get_ports tdo] 20.000
set_property src_info {type:XDC file:5 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_ports tms] 20.000
set_property src_info {type:XDC file:5 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_ports tdi] 20.000
set_property src_info {type:XDC file:5 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_ports trst_n] 20.000
set_property src_info {type:XDC file:5 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports trst_n]
set_property src_info {type:XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 100.000 -name tck -waveform {0.000 50.000} [get_ports tck]
set_property src_info {type:XDC file:6 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock tck -clock_fall 5.000 [get_ports tdi]
set_property src_info {type:XDC file:6 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock tck -clock_fall 5.000 [get_ports tms]
set_property src_info {type:XDC file:6 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock tck 5.000 [get_ports tdo]
set_property src_info {type:XDC file:6 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports trst_n]
set_property src_info {type:XDC file:6 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_pins {i_rstgen_main/i_rstgen_bypass/synch_regs_q_reg[3]/C}] 4
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_axi_dwidth_converter_dm_master]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_axi_dwidth_converter_dm_slave]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_xlnx_blk_mem_gen]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_xlnx_clk_gen]
